# Generated by Django 3.2.4 on 2021-06-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_delete_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryLevel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_level1', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_level1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_industries', to='database.industrylevel1'),
        ),
    ]
