# Generated by Django 3.2.4 on 2021-07-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210630_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='industry_level1',
            new_name='industry_level_1',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='industry_level2',
            new_name='industry_level_2',
        ),
        migrations.RenameField(
            model_name='industrylevel1',
            old_name='industry_level1',
            new_name='industry_level_1',
        ),
    ]
