# Generated by Django 3.2.4 on 2021-07-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210701_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.AddField(
            model_name='company',
            name='code_fiin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='code_vs',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
