# Generated by Django 3.2.4 on 2021-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20210715_0449'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('statement_categories', 'statement_name'), name='unique_statement'),
        ),
    ]
