# Generated by Django 3.2.4 on 2021-07-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_statement_unique_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='statement_categories',
            new_name='statement_category',
        ),
    ]
