# Generated by Django 3.2.4 on 2021-07-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_statement_categories_statement_statement_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='statement',
            name='unique_statement',
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('statement_category', 'statement_name'), name='unique_statement'),
        ),
    ]
